### ISSUE TITLE
`parsed` doesn't working

### ISSUE THREAD

**Issue by Egorundel** [cyrusbehr/tensorrt-cpp-api#20]
Hello!
Why **parsed** doesn't working?

![Screenshot from 2023-09-14 09-32-07](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/65890558/1fb7fca1-2764-4cd1-86fd-b4b84e75c799)

**Comment by cyrusbehr** [comment]
Upload your model file.

**Comment by Egorundel** [comment]
@cyrusbehr 
[YOLOv8-dbs-dbd.onnx (Google Drive)](https://drive.google.com/file/d/1vkAocljbZds2OOii8j1Bki4sndbSdA84/view?usp=drive_link)

[YOLOv8-dbs-dbd.trt (Google Drive)](https://drive.google.com/file/d/1AIuOFchLXPvGRPgvZlw9zTwq_96FXBbC/view?usp=drive_link)

**Comment by cyrusbehr** [comment]
I tested your model YOLOv8-dbs-dbd.onnx model. It is able to parse on my end. It however does fail later on because your model has a dynamic input width and height: 
![image](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/17056751/4923fedd-640a-418e-8408-ff96a3cc9e6e)

My implementation currently only supports models with fixed width and height: 
![image](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/17056751/e33aca28-3cfb-4e31-8498-8eeb24f3832d)


For a tutorial on how to use YoloV8, please see my other project: https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP
